In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
import category_encoders as ce
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [201]:
trainf = pd.read_csv('train_features.csv')
traintar = pd.read_csv('train_labels.csv')

testf = pd.read_csv('test_features.csv')

In [202]:
pd.options.display.max_rows = 100
pd.options.display.max_columns = 500

In [203]:
trainf.shape, traintar.shape, testf.shape

((59400, 40), (59400, 2), (14358, 40))

In [204]:
traintar['status_bin'] = traintar['status_group'].replace({'functional':1,
                                                           'functional needs repair':0, 
                                                           'non functional': 0})
traintar['status_bool'] = traintar['status_bin'].astype(bool)

traintar['status_ord'] = traintar['status_group'].replace({'functional':2,
                                                           'functional needs repair':1, 
                                                           'non functional': 0})

In [205]:
trainf.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe

In [108]:
Xtr.head(50)

,id,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,construction_year,waterpoint_type_group_communal standpipe,waterpoint_type_group_hand pump,waterpoint_type_group_other,waterpoint_type_group_improved spring,waterpoint_type_group_cattle trough,waterpoint_type_group_dam,waterpoint_type_group_-1,source_enc
3607,454,50.0,2092,35.426020,-4.227446e+00,0,21,1,160,1998,1,0,0,0,0,0,0,1
50870,510,0.0,0,35.510074,-5.724555e+00,0,1,6,0,0,0,1,0,0,0,0,0,1
20413,14146,0.0,0,32.499866,-9.081222e+00,0,12,6,0,0,0,0,1,0,0,0,0,1
52806,47410,0.0,0,34.060484,-8.830208e+00,0,12,7,0,0,1,0,0,0,0,0,0,0
50091,1288,300.0,1023,37.032690,-6.040787e+00,0,5,1,120,1997,0,0,1,0,0,0,0,1
16521,13095,0.0,0,33.509112,-2.648505e+00,0,19,2,0,0,0,1,0,0,0,0,0,1
52225,558,0.0,0,33.731347,-3.284633e+00,0,17,2,0,0,0,1,0,0,0,0,0,1
9440,35626,0.0,298,36.864072,-7.935517e+00,0,5,3,250,2009,0,1,0,0,0,0,0,1
41885,8696,0.0,0,33.423658,-2.606991e+00,0,19,2,0,0,1,0,0,0,0,0,0,1
54042,48650,0.0,1141,30.381136,-4.640729e+00,0,16,2,1520,2009,0,1,0,0,0,0,0,1
2732,61055,0.0,306,38.558271,-5.132980e+00,0,4,2,500,2008,0,0,1,0,0,0,0,1
36783,27298,0.0,365,38.328047,-5.019618e+00,0,4,2,150,2004,0,1,0,0,0,0,0,1
23198,52899,0.0,1572,35.058371,-8.217479e+00,0,11,2,0,0,0,1,0,0,0,0,0,1
2624,61616,0.0,0,33.519376,-3.225549e+00,0,17,2,0,0,0,0,1,0,0,0,0,1
35833,54295,0.0,1510,36.699314,-3.339683e+00,0,2,2,150,1998,1,0,0,0,0,0,0,1
22823,18191,0.0,0,0.000000,-2.000000e-08,0,17,1,0,0,0,1,0,0,0,0,0,1
22921,22057,0.0,0,33.585410,-9.240969e+00,0,12,4,0,0,1,0,0,0,0,0,0,1
20357,39797,0.0,0,31.425592,-1.211074e+00,0,18,7,0,0,0,1,0,0,0,0,0,1
35940,20856,0.0,0,35.970383,-6.679067e+00,0,1,4,0,0,1,0,0,0,0,0,0,1
18591,59340,0.0,0,0.000000,-2.000000e-08,0,17,1,0,0,0,1,0,0,0,0,0,1
8850,52944,0.0,1478,36.922038,-3.261929e+00,0,2,7,95,2012,1,0,0,0,0,0,0,1
35806,8638,0.0,1588,34.920112,-4.485898e+00,0,13,2,430,2010,1,0,0,0,0,0,0,1
26971,6390,0.0,0,33.143206,-9.342734e+00,0,12,5,0,0,1,0,0,0,0,0,0,1
20066,39662,0.0,0,33.168247,-4.453132e+00,0,14,1,0,0,1,0,0,0,0,0,0,0
54408,69518,0.0,0,32.955944,-2.533517e+00,0,19,8,0,0,0,0,1,0,0,0,0,1
19553,15222,0.0,0,33.143039,-3.883174e+00,0,17,3,0,0,1,0,0,0,0,0,0,0
5354,37453,0.0,2047,34.539695,-9.252128e+00,0,11,4,20,1985,1,0,0,0,0,0,0,1
15879,9535,0.0,0,0.000000,-2.000000e-08,0,17,1,0,0,0,1,0,0,0,0,0,1
38499,51552,0.0,0,34.381677,-8.711973e+00,0,12,7,0,0,1,0,0,0,0,0,0,0
31196,3903,10.0,1052,36.957172,-3.398525e+00,0,2,7,126,2003,1,0,0,0,0,0,0,0
17252,62063,0.0,0,33.560490,-9.250031e+00,0,12,4,0,0,1,0,0,0,0,0,0,1
35979,4773,0.0,0,33.808619,-9.182979e+00,0,12,4,0,0,1,0,0,0,0,0,0,0
45688,31083,0.0,0,33.578379,-3.133621e+00,0,17,2,0,0,0,1,0,0,0,0,0,1
28294,74051,0.0,388,38.489014,-5.010310e+00,0,4,2,300,2008,0,1,0,0,0,0,0,1
41138,55030,0.0,0,31.759504,-2.635426e+00,0,18,8,0,0,1,0,0,0,0,0,0,1
50968,46989,0.0,0,33.215442,-4.028820e+00,0,14,1,0,0,0,1,0,0,0,0,0,1
8322,35395,0.0,0,0.000000,-2.000000e-08,0,17,1,0,0,0,1,0,0,0,0,0,1
9750,56429,0.0,0,0.000000,-2.000000e-08,0,17,1,0,0,1,0,0,0,0,0,0,0
37087,70752,0.0,1403,36.694239,-3.037111e+00,0,2,6,250,1995,1,0,0,0,0,0,0,0
2211,28094,8000.0,1203,31.197379,-6.221130e+00,0,15,1,350,1985,0,1,0,0,0,0,0,1
29775,9852,0.0,-24,39.261596,-7.638440e+00,0,60,53,1,1997,0,0,1,0,0,0,0,1
51371,9196,0.0,0,0.000000,-2.000000e-08,0,19,2,0,0,0,1,0,0,0,0,0,1
7519,49980,0.0,1624,36.674364,-3.313979e+00,0,2,2,300,2012,1,0,0,0,0,0,0,1
20210,22255,0.0,-13,38.849396,-6.546033e+00,0,6,1,50,2008,0,1,0,0,0,0,0,1
25910,67492,0.0,0,31.632637,-2.948566e+00,0,18,8,0,0,0,1,0,0,0,0,0,1
41673,47079,250.0,2304,33.965132,-9.246824e+00,0,11,3,0,1986,1,0,0,0,0,0,0,1
57763,59437,0.0,0,33.563778,-3.050541e+00,0,17,2,0,0,0,0,1,0,0,0,0,1
42109,52900,0.0,477,34.704549,-1.115303e+01,0,10,3,50,1992,1,0,0,0,0,0,0,1
33664,25233,0.0,0,33.453952,-2.862311e+00,0,19,4,0,0,0,1,0,0,0,0,0,1
32654,38113,0.0,-35,39.363812,-6.864250e+00,0,7,3,140,1970,0,0,1,0,0,0,0,1

In [172]:
trainf['extraction_type_class'].value_counts()

gravity         26780
handpump        16456
other            6430
submersible      6179
motorpump        2987
rope pump         451
wind-powered      117
Name: extraction_type_class, dtype: int64

In [110]:
trainf['waterpoint_type_group'].value_counts()

communal standpipe    34625
hand pump             17488
other                  6380
improved spring         784
cattle trough           116
dam                       7
Name: waterpoint_type_group, dtype: int64

In [207]:
encoder_ord = ce.OrdinalEncoder()
encoded2 = encoder_ord.fit_transform(trainf[['quality_group']])
encoded2_columns = encoded2.columns
trainf['quality_ord'] = encoded2[encoded2_columns]

print(encoded2[1:10])

encoded2 = encoder_ord.transform(testf[['quality_group']])
encoded2_columns = encoded2.columns
testf['quality_ord'] = encoded2[encoded2_columns]


print(encoded2.head())

   quality_group
1              1
2              1
3              1
4              1
5              2
6              1
7              3
8              2
9              1
   quality_group
0              1
1              1
2              1
3              1
4              1

In [198]:
trainf.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,waterpoint_type_group_communal standpipe,waterpoint_type_group_hand pump,waterpoint_type_group_other,waterpoint_type_group_improved spring,waterpoint_type_group_cattle trough,waterpoint_type_group_dam,waterpoint_type_group_-1,quality_ord,region_Iringa,region_Mara,region_Manyara,region_Mtwara,region_Kagera,region_Tanga,region_Shinyanga,region_Tabora,region_Pwani,region_Ruvuma,region_Kilimanjaro,region_Rukwa,region_Mwanza,region_Kigoma,region_Lindi,region_Dodoma,region_Arusha,region_Mbeya,region_Singida,region_Morogoro,region_Dar es Salaam,region_-1,extraction_type_enc
0,50785.0,0.0,2013-02-04,Dmdd,1996.0,38776.539326,35.290799,-4.059696,Dinamu Secondary School,0.0,Internal,Magoma,Manyara,21.0,3.0,Mbulu,Bashay,321.0,True,GeoData Consultants Ltd,Parastatal,NaN,True,2012.0,other,36632.314308,other,37173.803167,parastatal,never pay,never pay,soft,good,seasonal,seasonal,36656.198257,rainwater harvesting,surface,other,other,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37108.084992
1,51630.0,0.0,2013-02-04,Government Of Tanzania,1569.0,36899.469544,36.656709,-3.309214,Kimnyak,0.0,Pangani,Kimnyak,Arusha,2.0,2.0,Arusha Rural,Kimnyaki,300.0,True,GeoData Consultants Ltd,VWC,TPRI pipe line,True,2000.0,gravity,37109.297237,gravity,37179.340632,user-group,never pay,never pay,soft,good,insufficient,insufficient,37230.863345,spring,groundwater,communal standpipe,communal standpipe,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,37110.355278
2,17168.0,0.0,2013-02-01,NaN,1567.0,37115.131768,34.767863,-5.004344,Puma Secondary,0.0,Internal,Msatu,Singida,13.0,2.0,Singida Rural,Puma,500.0,True,GeoData Consultants Ltd,VWC,P,NaN,2010.0,other,36632.314308,other,37179.340632,user-group,never pay,never pay,soft,good,insufficient,insufficient,36656.198257,rainwater harvesting,surface,other,other,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,37109.401770
3,45559.0,0.0,2013-01-22,Finn Water,267.0,32337.636364,38.058046,-9.418672,Kwa Mzee Pange,0.0,Ruvuma / Southern Coast,Kipindimbi,Lindi,80.0,43.0,Liwale,Mkutano,250.0,NaN,GeoData Consultants Ltd,VWC,NaN,True,1987.0,other,36632.314308,other,37179.340632,user-group,unknown,unknown,soft,good,dry,dry,37016.046184,shallow well,groundwater,other,other,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37221.401101
4,49871.0,500.0,2013-03-27,Bruder,1260.0,31760.875000,35.006123,-10.950412,Kwa Mzee Turuka,0.0,Ruvuma / Southern Coast,Losonga,Ruvuma,10.0,3.0,Mbinga,Mbinga Urban,60.0,NaN,GeoData Consultants Ltd,Water Board,BRUDER,True,2000.0,gravity,37109.297237,gravity,36306.338902,user-group,pay monthly,monthly,soft,good,enough,enough,37230.863345,spring,groundwater,communal standpipe,communal standpipe,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37109.946301

In [208]:
encoder_loo = ce.LeaveOneOutEncoder(verbose=10, cols=['installer','management','''extraction_type_group']).fit(trainf, traintar)

KeyError: ('installer', 'management', 'extraction_type_group')

In [196]:
encoder3 = encoder_loo.transform(trainf['installer','management','extraction_type_group'])
encoded3_columns = encoded3.columns
trainf[encoded3_columns] = encoded3[encoded3_columns]


encoded3 = encoder_loo.transform(testf['installer','management','extraction_type_group'])
encoded3_columns = encoded3.columns
testf[encoded3_columns] = encoded3[encoded3_columns]


print(encoded3[encoded_columns])

/home/joe2/anaconda3/lib/python3.7/site-packages/pandas/core/ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

KeyboardInterrupt:

In [100]:
trainf['quality_group'].value_counts()

good        50818
salty        5195
unknown      1876
milky         804
colored       490
fluoride      217
Name: quality_group, dtype: int64

In [50]:
trainf['source_enc'] = trainf['source_class'].replace({'unknown':0, 'surface':0, 'groundwater':1})
testf['source_enc'] = testf['source_class'].replace({'unknown':0, 'surface':0, 'groundwater':1})

In [152]:
encoder_oh = ce.OneHotEncoder(use_cat_names=True)
encoded = encoder_oh.fit_transform(trainf[['waterpoint_type_group', 'region']])
encoded_columns = encoded.columns
trainf[encoded_columns] = encoded[encoded_columns]

encoder_oh = ce.OneHotEncoder(use_cat_names=True)
encoded = encoder_oh.fit_transform(testf[['waterpoint_type_group', 'region']])
encoded_columns = encoded.columns
testf[encoded_columns] = encoded[encoded_columns]

In [193]:
Xtr.head()

,amount_tsh,gps_height,num_private,district_code,population,construction_year,waterpoint_type_group_communal standpipe,waterpoint_type_group_hand pump,waterpoint_type_group_other,waterpoint_type_group_improved spring,waterpoint_type_group_cattle trough,waterpoint_type_group_dam,waterpoint_type_group_-1,quality_ord,region_Iringa,region_Mara,region_Manyara,region_Mtwara,region_Kagera,region_Tanga,region_Shinyanga,region_Tabora,region_Pwani,region_Ruvuma,region_Kilimanjaro,region_Rukwa,region_Mwanza,region_Kigoma,region_Lindi,region_Dodoma,region_Arusha,region_Mbeya,region_Singida,region_Morogoro,region_Dar es Salaam,region_-1,extraction_type_enc
3607,50.0,2092,0,1,160,1998,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,37110.666044
50870,0.0,0,0,6,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,37653.992080
20413,0.0,0,0,6,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,36635.811946
52806,0.0,0,0,7,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,37108.912581
50091,300.0,1023,0,1,120,1997,0,0,1,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,36637.811946

In [199]:
features_all = trainf.columns

features_nonull = trainf.dropna(axis=1).columns

features_numeric = (trainf.drop(['id',
                                'longitude',
                                'latitude', 
                                'region_code']
                               , axis=1)
                    .select_dtypes(include='number')
                    .columns)


X = trainf[features_numeric]
y = traintar['status_ord']

Xtr, Xval, ytr, yval = train_test_split(X, y, 
                                        train_size=.80, 
                                        test_size=.20, 
                                        random_state=42)

Xte = testf[features_numeric]

In [200]:
Xtr.head()

,amount_tsh,gps_height,installer,num_private,district_code,population,construction_year,extraction_type_group,management,source,waterpoint_type_group_communal standpipe,waterpoint_type_group_hand pump,waterpoint_type_group_other,waterpoint_type_group_improved spring,waterpoint_type_group_cattle trough,waterpoint_type_group_dam,waterpoint_type_group_-1,quality_ord,region_Iringa,region_Mara,region_Manyara,region_Mtwara,region_Kagera,region_Tanga,region_Shinyanga,region_Tabora,region_Pwani,region_Ruvuma,region_Kilimanjaro,region_Rukwa,region_Mwanza,region_Kigoma,region_Lindi,region_Dodoma,region_Arusha,region_Mbeya,region_Singida,region_Morogoro,region_Dar es Salaam,region_-1,extraction_type_enc
3607,0.0,0.0,36899.469544,0.0,7.0,1000.0,2003.0,37109.297237,37179.340632,36656.198257,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37110.666044
50870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [131]:
from scipy.stats import randint

In [189]:
pdist = {
    'n_estimators': randint(225,280),
    'max_depth': randint(4,8)
}

search = RandomizedSearchCV(
    estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
    param_distributions=pdist,
    n_iter=5,
    n_jobs=4,
    cv=3,
    scoring='accuracy',
    verbose=10,
    return_train_score=True
)
search.fit(Xtr, ytr)

Fitting 3 folds for each of 5 candidates, totalling 15 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   5 tasks      | elapsed:   19.8s
[Parallel(n_jobs=4)]: Done  10 out of  15 | elapsed:   30.5s remaining:   15.3s
[Parallel(n_jobs=4)]: Done  12 out of  15 | elapsed:   32.0s remaining:    8.0s
[Parallel(n_jobs=4)]: Done  15 out of  15 | elapsed:   36.2s finished

RandomizedSearchCV(cv=3, error_score='raise-deprecating',
          estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=-1,
            oob_score=False, random_state=42, verbose=0, warm_start=False),
          fit_params=None, iid='warn', n_iter=5, n_jobs=4,
          param_distributions={'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f889f2b8780>, 'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f889f2b8278>},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score=True, scoring='accuracy', verbose=10)

In [190]:
print('Cross-Validation accuracy score:', search.best_score_)

Cross-Validation accuracy score: 0.6761784511784512

In [191]:
best = search.best_estimator_
ypred = best.predict(Xval)
accuracy_score(ypred, yval)

0.6781144781144781

In [169]:
ypred_test = pd.Series(best.predict(Xte))

In [93]:


better_submit = pd.DataFrame({'id':Xte['id'], 'status_group':ypred_test.replace({2:'functional',
                                                           1:'functional needs repair', 
                                                           0:'non functional'})})
better_submit.to_csv('joebender_rforest1.csv', index=False)